# Generated by Django 5.2.7 on 2026-01-25 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contas', '0007_alter_cadastro_matricula'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('empresa', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('requisitos', models.TextField(blank=True, help_text='Detalhes extras além das skills', null=True)),
                ('tipo', models.CharField(choices=[('ESTAGIO', 'Estágio'), ('JUNIOR', 'Júnior'), ('PLENO', 'Pleno'), ('SENIOR', 'Sênior')], default='ESTAGIO', max_length=20)),
                ('status', models.CharField(choices=[('ATIVA', 'Disponível'), ('PAUSADA', 'Em Espera'), ('FECHADA', 'Encerrada')], default='ATIVA', max_length=20)),
                ('data_limite', models.DateField(blank=True, null=True)),
                ('link_externo', models.URLField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('habilidades', models.ManyToManyField(blank=True, related_name='vagas', to='contas.habilidade')),
                ('professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vagas_criadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Candidatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_aplicacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ENVIADO', 'Candidatura Enviada'), ('VISUALIZADO', 'Visualizado'), ('ENTREVISTA', 'Entrevista'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Não Selecionado')], default='ENVIADO', max_length=20)),
                ('match_percent', models.IntegerField(default=0, help_text='Porcentagem de match calculada')),
                ('curriculo_pdf', models.FileField(blank=True, null=True, upload_to='curriculos/')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minhas_candidaturas', to=settings.AUTH_USER_MODEL)),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatos', to='vagas.vaga')),
            ],
            options={
                'unique_together': {('aluno', 'vaga')},
            },
        ),
    ]
