# Generated by Django 5.2.7 on 2026-01-25 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatura',
            name='match_percent',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='requisitos',
            field=models.TextField(blank=True, null=True),
        ),
    ]
