# Generated by Django 5.2.7 on 2026-01-26 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0002_alter_candidatura_match_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='cidade',
            field=models.CharField(default='Não informada', max_length=100),
        ),
        migrations.AddField(
            model_name='vaga',
            name='modalidade',
            field=models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('HIBRIDO', 'Híbrido'), ('REMOTO', 'Remoto')], default='PRESENCIAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='descricao',
            field=models.TextField(verbose_name='Sobre a Vaga'),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='status',
            field=models.CharField(choices=[('ABERTA', 'Aberta'), ('EM_ANDAMENTO', 'Em Andamento (Futuro)'), ('EM_ESPERA', 'Em Espera'), ('CANCELADA', 'Cancelada'), ('FECHADA', 'Encerrada')], default='ABERTA', max_length=20),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Cargo'),
        ),
    ]
