# Generated by Django 5.2.7 on 2025-11-04 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nome_cadastro', models.CharField(max_length=45)),
                ('matricula', models.IntegerField(unique=True)),
                ('campus', models.CharField(max_length=30)),
                ('tipoDoCadastro', models.IntegerField(choices=[(1, 'Aluno'), (2, 'Professor')], default=1)),
            ],
        ),
    ]
