# Generated by Django 5.2.7 on 2025-11-08 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cadastro',
            old_name='nome_cadastro',
            new_name='nome',
        ),
    ]
