# Generated by Django 5.2.7 on 2026-01-21 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_habilidade_habilidadealuno_perfilaluno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HabilidadeDestaque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.TextField(max_length=150)),
                ('cor', models.CharField(default='gray', max_length=20)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habilidades_destaque', to='contas.perfilaluno')),
            ],
        ),
    ]
