# Generated by Django 5.2.7 on 2026-01-22 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0004_habilidadedestaque'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('instituicao', models.CharField(max_length=50)),
                ('horas', models.CharField(blank=True, max_length=20, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='contas.perfilaluno')),
            ],
        ),
    ]
