# Generated by Django 5.2.7 on 2026-01-23 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0005_certificado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificado',
            name='link',
        ),
        migrations.AddField(
            model_name='certificado',
            name='link_certificado',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
