# Generated by Django 5.2.7 on 2026-01-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0006_remove_certificado_link_certificado_link_certificado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='matricula',
            field=models.BigIntegerField(unique=True),
        ),
    ]
